//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotepadServiceRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.GroupUser = new HashSet<GroupUser>();
            this.Note = new HashSet<Note>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<GroupUser> GroupUser { get; set; }
        public virtual ICollection<Note> Note { get; set; }
    }
}
